# fly.toml app configuration file generated for ai-money-bot on 2026-07-04T14:39:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-money-bot'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
